name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/docker_build_push.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate metadata
        id: metadata
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "FULL_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and test
        id: docker_build
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          push: false
          load: true
          tags: test-image:${{ env.SHORT_SHA }}
          
      - name: Create test summary
        if: steps.docker_build.outcome == 'failure'
        run: |
          echo "## Test Results :test_tube:" >> $GITHUB_STEP_SUMMARY
          echo "Tests failed during docker build. Output from tests:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          docker build . 2>&1 | grep -A 50 "Starting test execution" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Push images
        if: steps.docker_build.outcome == 'success'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:sha-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.FULL_SHA }}